apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: expense-app

resources:
- ../namespace.yaml
- ../configmap.yaml
- ../deployment.yaml
- ../loadbalancer.yaml

patches:
- target:
    kind: Deployment
    name: expense-app
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: your-registry.ocir.io/expense-app:latest
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always

commonLabels:
  app: expense-app
  environment: oke
