apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: expense-app

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: expense-app
  version: v1.0.0
